apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yv48cdrmd-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yv48cdrmd-go 
  name: yv48cdrmd-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yv48cdrmd-go 
